# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-5659-fitz-Computer/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/vivado_build
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/led
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/gpio
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/uart
  } -define SRAM_INIT_FILE=../vivado_build/../software/led/led.vmem {
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/clkgen_xil7series.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/complex_core.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/data_ram.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_pkg.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_alu.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_compressed_decoder.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_controller.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_core.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_cs_registers.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_decoder.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_ex_block.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_fetch_fifo.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_id_stage.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_if_stage.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_load_store_unit.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_multdiv_fast.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_multdiv_slow.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_pmp.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_prefetch_buffer.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ibex_register_file_ff.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/lint_bridge/lint_2_apb.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/peripherals.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/peripherals_interconnect.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/prim_clock_gating.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/ram_1p.sv
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/top_artya7_100.sv
      /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/vivado_build
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/led
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/gpio
    /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/software/uart
  } -define SRAM_INIT_FILE=../vivado_build/../software/led/led.vmem {
      ./.Xil/Vivado-5659-fitz-Computer/realtime/mmcm_stub.v
      ./.Xil/Vivado-5659-fitz-Computer/realtime/blk_mem_gen_0_stub.v
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/micro_uart/hdl/micro_uart3.v
      /home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/micro_uart/hdl/micro_uart3_apb.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_fpga
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5659-fitz-Computer/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
