# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr.xci
# IP: The module: 'sys_reset_n4ddr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr.xci
# IP: The module: 'sys_reset_n4ddr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/sources_1/ip/sys_reset_n4ddr/sys_reset_n4ddr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_reset_n4ddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
