set_property SRC_FILE_INFO {cfile:/home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/rtl/mmcm/mmcm.xdc rfile:../../rtl/mmcm/mmcm.xdc id:1 order:EARLY scoped_inst:clkgen/u_mmcm/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/constraints/kc705.xdc rfile:../../constraints/kc705.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/fitz/FPGA/PROJ/lowrisc/hardware/ibex_soc/vivado_build/lowrisc_ibex_kc705.srcs/constrs_1/imports/constraints/top_fpga.xdc rfile:../lowrisc_ibex_kc705.srcs/constrs_1/imports/constraints/top_fpga.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.05
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mcu_clk [get_pins clkgen/u_mmcm/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list inst_peripherals/uart_0_interrupt]]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clkgen/u_mmcm/inst/clk_out1]]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst_complex_core/data_addr[0]} {inst_complex_core/data_addr[1]} {inst_complex_core/data_addr[2]} {inst_complex_core/data_addr[3]} {inst_complex_core/data_addr[4]} {inst_complex_core/data_addr[5]} {inst_complex_core/data_addr[6]} {inst_complex_core/data_addr[7]} {inst_complex_core/data_addr[8]} {inst_complex_core/data_addr[9]} {inst_complex_core/data_addr[10]} {inst_complex_core/data_addr[11]} {inst_complex_core/data_addr[12]} {inst_complex_core/data_addr[13]} {inst_complex_core/data_addr[14]} {inst_complex_core/data_addr[15]} {inst_complex_core/data_addr[16]} {inst_complex_core/data_addr[17]} {inst_complex_core/data_addr[18]} {inst_complex_core/data_addr[19]} {inst_complex_core/data_addr[20]} {inst_complex_core/data_addr[21]} {inst_complex_core/data_addr[22]} {inst_complex_core/data_addr[23]} {inst_complex_core/data_addr[24]} {inst_complex_core/data_addr[25]} {inst_complex_core/data_addr[26]} {inst_complex_core/data_addr[27]} {inst_complex_core/data_addr[28]} {inst_complex_core/data_addr[29]} {inst_complex_core/data_addr[30]} {inst_complex_core/data_addr[31]}]]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst_complex_core/data_be[0]} {inst_complex_core/data_be[1]} {inst_complex_core/data_be[2]} {inst_complex_core/data_be[3]}]]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {inst_complex_core/instr_addr[0]} {inst_complex_core/instr_addr[1]} {inst_complex_core/instr_addr[2]} {inst_complex_core/instr_addr[3]} {inst_complex_core/instr_addr[4]} {inst_complex_core/instr_addr[5]} {inst_complex_core/instr_addr[6]} {inst_complex_core/instr_addr[7]} {inst_complex_core/instr_addr[8]} {inst_complex_core/instr_addr[9]} {inst_complex_core/instr_addr[10]} {inst_complex_core/instr_addr[11]} {inst_complex_core/instr_addr[12]} {inst_complex_core/instr_addr[13]} {inst_complex_core/instr_addr[14]} {inst_complex_core/instr_addr[15]} {inst_complex_core/instr_addr[16]} {inst_complex_core/instr_addr[17]} {inst_complex_core/instr_addr[18]} {inst_complex_core/instr_addr[19]} {inst_complex_core/instr_addr[20]} {inst_complex_core/instr_addr[21]} {inst_complex_core/instr_addr[22]} {inst_complex_core/instr_addr[23]} {inst_complex_core/instr_addr[24]} {inst_complex_core/instr_addr[25]} {inst_complex_core/instr_addr[26]} {inst_complex_core/instr_addr[27]} {inst_complex_core/instr_addr[28]} {inst_complex_core/instr_addr[29]} {inst_complex_core/instr_addr[30]} {inst_complex_core/instr_addr[31]}]]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {inst_complex_core/data_rdata[0]} {inst_complex_core/data_rdata[1]} {inst_complex_core/data_rdata[2]} {inst_complex_core/data_rdata[3]} {inst_complex_core/data_rdata[4]} {inst_complex_core/data_rdata[5]} {inst_complex_core/data_rdata[6]} {inst_complex_core/data_rdata[7]} {inst_complex_core/data_rdata[8]} {inst_complex_core/data_rdata[9]} {inst_complex_core/data_rdata[10]} {inst_complex_core/data_rdata[11]} {inst_complex_core/data_rdata[12]} {inst_complex_core/data_rdata[13]} {inst_complex_core/data_rdata[14]} {inst_complex_core/data_rdata[15]} {inst_complex_core/data_rdata[16]} {inst_complex_core/data_rdata[17]} {inst_complex_core/data_rdata[18]} {inst_complex_core/data_rdata[19]} {inst_complex_core/data_rdata[20]} {inst_complex_core/data_rdata[21]} {inst_complex_core/data_rdata[22]} {inst_complex_core/data_rdata[23]} {inst_complex_core/data_rdata[24]} {inst_complex_core/data_rdata[25]} {inst_complex_core/data_rdata[26]} {inst_complex_core/data_rdata[27]} {inst_complex_core/data_rdata[28]} {inst_complex_core/data_rdata[29]} {inst_complex_core/data_rdata[30]} {inst_complex_core/data_rdata[31]}]]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {inst_complex_core/data_wdata[0]} {inst_complex_core/data_wdata[1]} {inst_complex_core/data_wdata[2]} {inst_complex_core/data_wdata[3]} {inst_complex_core/data_wdata[4]} {inst_complex_core/data_wdata[5]} {inst_complex_core/data_wdata[6]} {inst_complex_core/data_wdata[7]} {inst_complex_core/data_wdata[8]} {inst_complex_core/data_wdata[9]} {inst_complex_core/data_wdata[10]} {inst_complex_core/data_wdata[11]} {inst_complex_core/data_wdata[12]} {inst_complex_core/data_wdata[13]} {inst_complex_core/data_wdata[14]} {inst_complex_core/data_wdata[15]} {inst_complex_core/data_wdata[16]} {inst_complex_core/data_wdata[17]} {inst_complex_core/data_wdata[18]} {inst_complex_core/data_wdata[19]} {inst_complex_core/data_wdata[20]} {inst_complex_core/data_wdata[21]} {inst_complex_core/data_wdata[22]} {inst_complex_core/data_wdata[23]} {inst_complex_core/data_wdata[24]} {inst_complex_core/data_wdata[25]} {inst_complex_core/data_wdata[26]} {inst_complex_core/data_wdata[27]} {inst_complex_core/data_wdata[28]} {inst_complex_core/data_wdata[29]} {inst_complex_core/data_wdata[30]} {inst_complex_core/data_wdata[31]}]]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {inst_complex_core/instr_rdata[0]} {inst_complex_core/instr_rdata[1]} {inst_complex_core/instr_rdata[2]} {inst_complex_core/instr_rdata[3]} {inst_complex_core/instr_rdata[4]} {inst_complex_core/instr_rdata[5]} {inst_complex_core/instr_rdata[6]} {inst_complex_core/instr_rdata[7]} {inst_complex_core/instr_rdata[8]} {inst_complex_core/instr_rdata[9]} {inst_complex_core/instr_rdata[10]} {inst_complex_core/instr_rdata[11]} {inst_complex_core/instr_rdata[12]} {inst_complex_core/instr_rdata[13]} {inst_complex_core/instr_rdata[14]} {inst_complex_core/instr_rdata[15]} {inst_complex_core/instr_rdata[16]} {inst_complex_core/instr_rdata[17]} {inst_complex_core/instr_rdata[18]} {inst_complex_core/instr_rdata[19]} {inst_complex_core/instr_rdata[20]} {inst_complex_core/instr_rdata[21]} {inst_complex_core/instr_rdata[22]} {inst_complex_core/instr_rdata[23]} {inst_complex_core/instr_rdata[24]} {inst_complex_core/instr_rdata[25]} {inst_complex_core/instr_rdata[26]} {inst_complex_core/instr_rdata[27]} {inst_complex_core/instr_rdata[28]} {inst_complex_core/instr_rdata[29]} {inst_complex_core/instr_rdata[30]} {inst_complex_core/instr_rdata[31]}]]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list inst_complex_core/data_gnt]]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list inst_complex_core/data_req]]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list inst_complex_core/data_rvalid]]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list inst_complex_core/data_we]]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list inst_complex_core/instr_gnt]]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list inst_complex_core/instr_req]]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list inst_complex_core/instr_rvalid]]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list inst_peripherals/timer_0_irq]]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list inst_peripherals/uart_0_irq]]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list uart_rx_i_IBUF]]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list uart_tx_o_OBUF]]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_sys]
