webtalk_init -webtalk_dir /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.sim/sim_1/behav/xsim/xsim.dir/tb_n4ddr_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 27 17:55:00 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9e4f3706-4079-46f7-b0bf-b3f1c5d08f86" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "da6c373f9986482bb7514d6f81a454d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 1500X Quad-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1376.521 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "50.55_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "141548_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3591431623 -regid "" -xml /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.sim/sim_1/behav/xsim/xsim.dir/tb_n4ddr_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.sim/sim_1/behav/xsim/xsim.dir/tb_n4ddr_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fitz/FPGA/Project/ibex_soc/vivado_build/lowrisc_ibex_kc705.sim/sim_1/behav/xsim/xsim.dir/tb_n4ddr_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
