# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-7476-fitz-Computer/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/vivado_build
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/led
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/gpio
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/uart
  } -define SRAM_INIT_FILE=../vivado_build/../software/led/led.vmem {
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/adv_dbg_if/rtl/adbg_lint_biu.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/adv_dbg_if/rtl/adbg_lint_module.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/adv_dbg_if/rtl/adbg_lintonly_top.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb2per/apb2per.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_gpio/rtl/apb_gpio.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_channel/apb_node.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_channel/apb_node_wrap.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_soc_ctrl.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_timer/apb_timer.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/jtag_pulp/src/bscell.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/common_cells/src/cdc_2phase.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/clk_rst_n4ddr.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/clkdivider.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/tech_cells_generic/src/deprecated/cluster_clk_cells_xilinx.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/data_ram.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dm_pkg.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/debug_domain.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/debug_rom/debug_rom.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dm_csrs.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dm_mem.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dm_sba.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dm_top.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/dm_wallpaper.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dmi_cdc.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dmi_jtag.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/riscv_dbg/src/dmi_jtag_tap.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/common_cells/src/deprecated/fifo_v2.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/common_cells/src/fifo_v3.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/hold.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_pkg.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_alu.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_compressed_decoder.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_controller.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_core.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_cs_registers.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_decoder.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_ex_block.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_fetch_fifo.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_id_stage.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_if_stage.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_load_store_unit.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_multdiv_fast.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_multdiv_slow.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_pmp.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_prefetch_buffer.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ibex_register_file_ff.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/interfaces/interface.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/jtag_pulp/src/jtag_sync.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/jtag_tap_top.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/jtag_pulp/src/jtagreg.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/lint_bridge/lint_2_apb.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/lint_jtag_wrap.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/lint_bridge/lint_mux.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/lint_bridge/lint_slice.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_channel/periph_bus_wrap.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/peripherals.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/prim_clock_gating.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/ram_1p.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/soc_interconnect_wrap.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/soc_top.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/sram.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/tcdm_arbiter_2x1.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/apb_timer/timer.sv
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/n4ddr_top.sv
      /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/vivado_build
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/led
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/gpio
    /home/fitz/FPGA/lowrisc/hardware/ibex_soc/software/uart
  } -define SRAM_INIT_FILE=../vivado_build/../software/led/led.vmem {
      ./.Xil/Vivado-7476-fitz-Computer/realtime/blk_mem_gen_0_stub.v
      ./.Xil/Vivado-7476-fitz-Computer/realtime/mmcm_n4ddr_stub.v
      ./.Xil/Vivado-7476-fitz-Computer/realtime/sys_reset_n4ddr_stub.v
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/adv_dbg_if/rtl/adbg_crc32.v
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/micro_uart/hdl/micro_uart3.v
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/micro_uart/hdl/micro_uart3_apb.v
      /home/fitz/FPGA/lowrisc/hardware/ibex_soc/rtl/jtag_pulp/src/tap_top.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top n4ddr_top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-7476-fitz-Computer/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
